<?php echo $this->getChildHtml('sticky.nav') ?>
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $custom_block = Mage::getStoreConfig('porto_settings/header/static_block', $code);
?>
<div class="header-search">
    <div class="rightcontainer">
        <?php echo $this->getChildHtml('minicart'); ?>
        <div class="myaccount">
            <span class="text-mini-cart"><a href="<?php echo Mage::getUrl('customer/account'); ?>"><?php echo $this->__("My account"); ?></a></span>
            <div class="myaccountlink">
                <i class="icon-user"></i>
                <a href="/customer/account/">
                    <span class="account-info">
                    <?php echo $this->getStateTitle();?>
                </span>
                </a>
            </div>
            <div class="options">
                <?php echo $this->getChildHtml('topLinks'); ?>
            </div>
        </div>
    </div>    
    <div class="centercontainer">
        <div class="search-area">
            <a href="javascript:void(0);" class="search-icon"><i class="icon-search"></i></a>
            <?php echo $this->getChildHtml('topSearch'); ?>
        </div>
    </div>
    <div id="submenu-sual">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('extra_menu')->toHtml();?>
    </div>
</div>
<div class="header-container type12 <?php if(Mage::getStoreConfig('porto_settings/header/new_skin', $code)): ?>header-newskin<?php endif; ?>">
    <div class="header">
        <div class="switcher-area">
            <?php //echo $this->getChildHtml('store_currency'); ?>
            <?php //echo $this->getChildHtml('store_language'); ?>
            <?php //echo $this->getChildHtml('compare_link'); ?>
        </div>
        <?php if ($this->getIsHomePage()):?>
        <h1 class="logo">
            <strong><?php echo $this->getLogoAlt(); ?></strong>
                <img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" />


            <a href="javascript:void(0);" class="search-icon"><i class="icon-search"></i></a>
            <div class="menu-icon"><a href="javascript:void(0)" title="<?php echo $this->__('Menu'); ?>"><i class="fa fa-bars"></i></a></div>
        </h1>
        <?php else:?>
            <h1 class="logo">
            <strong><?php echo $this->getLogoAlt(); ?></strong>
            <a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo">
                <img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" />
            </a>

            <a href="javascript:void(0);" class="search-icon"><i class="icon-search"></i></a>
            <div class="menu-icon"><a href="javascript:void(0)" title="<?php echo $this->__('Menu'); ?>"><i class="fa fa-bars"></i></a></div>
        </h1>
        <?php endif; ?>
        <?php if(!Mage::getStoreConfig('porto_settings/header/new_skin', $code)): ?>
            <?php 
                $cacheId = 'top_menu';
                $cacheTag = 'block_html';
                if ($cachedTopMenu = Mage::app()->getCache()->load($cacheId)) {
                    $topMenu = unserialize($cachedTopMenu);
                } else {
                    $topMenu = $this->getChildHtml('topMenu');
                    Mage::app()->getCache()->save(serialize($topMenu), $cacheId, array($cacheTag));
                } 
                echo $topMenu;
            ?>
            <div class="mobile-group">
                <div class="search-area">
                    <a href="javascript:void(0);" class="search-icon"><i class="icon-search"></i></a>
                    <?php echo $this->getChildHtml('topSearch'); ?>
                </div>
                <div class="top-links-area">
                    <div class="top-links-icon"><a href="javascript:void(0)"><?php echo $this->__("links"); ?></a></div>
                    <?php echo $this->getChildHtml('topLinks'); ?>
                </div>
                <div class="menu-icon"><a href="javascript:void(0)" title="<?php echo $this->__('Menu'); ?>"><i class="fa fa-bars"></i></a></div>
            </div>
        <?php else: ?>
            <div class="search-area right-search">
                <?php echo $this->getChildHtml('topSearch'); ?>
            </div>
            <?php 
                $cacheId = 'top_menu';
                $cacheTag = 'block_html';
                if ($cachedTopMenu = Mage::app()->getCache()->load($cacheId)) {
                    $topMenu = unserialize($cachedTopMenu);
                } else {
                    $topMenu = $this->getChildHtml('topMenu');
                    Mage::app()->getCache()->save(serialize($topMenu), $cacheId, array($cacheTag));
                } 
                echo $topMenu;
            ?>
            <div class="mobile-group account-menu">
                <div class="top-links-area">
                    <div class="top-links-icon"><a href="javascript:void(0)"><?php echo $this->__("links"); ?></a></div>
                    <?php echo $this->getChildHtml('topLinks'); ?>
                </div>
            </div>
        <?php endif; ?>
        <div class="clearer"></div>

        <?php
        $cacheId = 'top_menu_mobile';
        $cacheTag = 'block_html';
        if ($cachedTopMenu = Mage::app()->getCache()->load($cacheId)) {
            $topMenuNav = unserialize($cachedTopMenu);
        } else {
            $topMenuNav = $this->getChildHtml('mobile.nav');
            Mage::app()->getCache()->save(serialize($topMenuNav), $cacheId, array($cacheTag));
        }
        echo $topMenuNav;
        ?>

        <?php
            $custom_block = Mage::getStoreConfig('porto_settings/header/static_block', $code);
        ?>
        <?php echo '<div class="custom-block">'.$this->getLayout()->createBlock('cms/block')->setBlockId($custom_block)->toHtml().'</div>'; ?>
    </div>
</div>